### ISSUE TITLE
Problem reestablishing connection to remote device after uploading new firmware

### ISSUE THREAD

**Issue by JulioDeLeon** [nerves-project/nerves_system_rpi0#103]
During Nerves workshop in Elixir Chicago,  I was using a Linux machine with the 4.20 kernel. I was able to connect to the provided device initially and upload firmware from the provided device example.

However, after the device rebooted with the new firmware, My machine could not reestablish a connection to the target device unless I rebooted my machine. This behaviour would repeat itself whenever I uploaded new firmware to the device.

**Comment by fhunleth** [comment]
Replicated many times. Thanks for creating this issue. I'll post as I find anything useful out.

**Comment by fhunleth** [comment]
I believe I found it. It's a combination of things:

1. In the current release, any connection to the virtual serial port will hang the USB connection
2. Even if you're not using the virtual serial port, ModemManager on Linux will probe the serial port to see if it's a cellular modem.
3. The first item is fixed if a process on the device would read from `/dev/ttyGS0`. Sometimes `/dev/ttyGS0` didn't exist so the call from `erlinit` to read it failed (but you couldn't see the failure since you couldn't connect). `erlinit` doesn't retry, but if it had, it would have fixed it.

Disabling ModemManager improved the situation, but obviously isn't a fix.

Finding number 3 above was the key. The `nbtty` program that we use to handle blocking behavior on the serial port also is able to retry opening device connections. See #106 for a fix that updates the configuration to do this.

It's also worth noting that I've seen another warning message about deferring the serial port initialization that bothers me. I don't know if it actually causes a problem, but it can be worked around by manually specifying kernel module load order.

I'm working on getting fixes out on all of this.

**Comment by fhunleth** [comment]
Oops - I missed closing this. This appears to be fixed in `v1.7.1`. It hasn't popped up since that was released to my knowledge.
