### ISSUE TITLE
Resize partitions for sdcard smaller than 1GB

### ISSUE THREAD

**Issue by adrienmo** [nerves-project/nerves_system_rpi0#134]
Hello guys, thanks for the amazing work!

I am looking for option to reduce the partition size to be able to use smaller and cheaper sdcard. I looked into the fwup.conf and it seems I could tweak this line:

https://github.com/nerves-project/nerves_system_rpi0/blob/master/fwup.conf#L81

What is being stored in the application partition ? As far as I understand it gets formatted on startup, so it should only be some extra data needed by the app, in my case I don't have any. Is it safe to resize it from 512 MB to let's say 64 MB ?

Thanks

**Comment by fhunleth** [comment]
Yes - totally safe. The only "official" uses of the application partition are to save IEx commandline history and for `vintage_net` to save network settings. Both uses are trivially small. If you're customizing the `fwup.conf`, then you can shrink the other partitions down as well. Since we have to pick sizes, we generally spaced things out.

Also, there was a feature added to `fwup` a year ago or so to automatically expand the application partition to fill the MicroSD card. It doesn't sound like application size is important to you, but if that changes, you could set that to be able to use both small and large MicroSD cards.
