### ISSUE TITLE
Application hangs when CDC serial device isn't connected to a host

### ISSUE THREAD

**Issue by tmecklem** [nerves-project/nerves_system_rpi0#30]
### Environment
* Erlang version 19.2, 20.0:
* Elixir version 1.4.5, 1.5.0:
* Operating system: N/A

### Current behavior

Under circumstances that can be difficult to reproduce, booting into a Nerves application on the nerves_system_rpio system that has a lot of logging information being sent to ttyGS0 can cause the application to hang. When the nerves device is plugged into a host machine and a screen session is connected to the device so that logs show up on the host, the application resumes running. The Nerves application will continue to run even if the screen session is terminated.

Include code samples, errors and stacktraces if appropriate.

This has been tricky to reproduce in a simple application, but I am still attempting it. I decided to log the issue to spur discussion and other potential examples of the behavior in the real world while I continue to work on a simple reproducible example.

### Expected behavior

The application will not hang, presumably while it's trying to write more log information to a buffer for ttyGS0.

**Comment by tmecklem** [comment]
There's been discussion of using a pty for the primary logging console, which might resolve this issue indirectly while providing more flexibility for logging output.

**Comment by fhunleth** [comment]
I have a prototype C program that I think fixes it. The code is at https://github.com/fhunleth/nbtty. The `nbtty` branch of `nerves_system_br` pulls it in for custom systems.

The prototype C program is a massive simplification on `dtach`. It has a few changes, but the most important one is that the pty given to Erlang will drop characters instead of blocking. Given the default amount of buffering, it doesn't seem to drop when `picocom` or `screen` read from the port. However, it drops tons when they aren't connected.

**Comment by fhunleth** [comment]
Closing this since `nbtty` has been in use for months with no new reports of hangs.
